{{- if and .Values.ingress.enabled (not (eq (include "mw.isOpenShift" .) "true")) }}
{{- $fullname := include "mw.fullname" . -}}
{{- $svc := dict
    "nextcloud"    (dict "name" (printf "%s-nextcloud-web" $fullname) "port" 80   "host" .Values.hosts.nextcloud)
    "mattermost"   (dict "name" (printf "%s-mattermost" $fullname)    "port" 8065 "host" .Values.hosts.mattermost)
    "collabora"    (dict "name" (printf "%s-collabora" $fullname)     "port" 9980 "host" .Values.hosts.collabora)
    "keycloak"     (dict "name" (printf "%s-keycloak" $fullname)      "port" 8080 "host" .Values.hosts.keycloak)
    "minio"        (dict "name" (printf "%s-minio" $fullname)         "port" 9001 "host" .Values.hosts.minioConsole)
-}}
{{- if .Values.homer.enabled }}
{{- $_ := set $svc "homer" (dict "name" (printf "%s-homer" $fullname) "port" 8080 "host" .Values.hosts.homer) -}}
{{- end }}
{{- if .Values.monitoring.enabled }}
{{- $_ := set $svc "grafana" (dict "name" (printf "%s-grafana" $fullname) "port" 3000 "host" .Values.hosts.grafana) -}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "mw.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- if .Values.ingress.tls.wildcardSecretName }}
    - hosts:
        {{- range $k, $v := $svc }}
        - {{ $v.host | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.wildcardSecretName | quote }}
    {{- else }}
    {{- range $k, $v := $svc }}
    - hosts: [{{ $v.host | quote }}]
      secretName: {{ printf "%s-tls" $v.host | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $k, $v := $svc }}
    - host: {{ $v.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $v.name }}
                port: { number: {{ $v.port }} }
    {{- end }}
{{- end }}
